FROM node:22.13.0-alpine

WORKDIR /app

COPY package*.json ./

COPY apps/shell/package*.json ./apps/shell/
COPY apps/transactions/package*.json ./apps/transactions/

RUN npm install

COPY . .

RUN npm run build --workspace @finance/transactions

EXPOSE 3001

CMD ["npm", "run", "start", "--workspace", "@finance/transactions"]